# Generated by Django 3.1.3 on 2020-12-11 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image2',
            field=models.ImageField(default='', null=True, upload_to='static/images/'),
        ),
        migrations.AddField(
            model_name='product',
            name='image3',
            field=models.ImageField(default='', null=True, upload_to='static/images/'),
        ),
    ]
